# Generated by Django 2.2.2 on 2019-07-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='owner',
            field=models.TextField(default='me'),
            preserve_default=False,
        ),
    ]
