# Generated by Django 2.2.2 on 2019-07-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_playlist_playlist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='lat',
            field=models.DecimalField(decimal_places=20, default=1.0, max_digits=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='long',
            field=models.DecimalField(decimal_places=20, default=1.234, max_digits=40),
            preserve_default=False,
        ),
    ]
