# Generated by Django 2.2.2 on 2019-07-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0005_auto_20190708_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='suser',
            name='user_name',
            field=models.TextField(default='John Doe'),
            preserve_default=False,
        ),
    ]
